[auth]
redirect_uri = "http://localhost:8501/oauth2callback"

[auth.oidc.brgxbqrxoz7r]
client_id = "6a0099b774fc964d8b9f9988"
client_secret = "5a184ba556296c78969cf7963722f69d"
server_metadata_url = "https://brgxbqrxoz7r-demo.authing.cn/oidc/.well-known/openid-configuration"